### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by cypri99** [Cryptolens/cryptolens-python#11]
Hello,

I don't understand why I get the following error. Thanks

Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/licensing/methods.py", line 139, in GetMachineCode
    return HelperMethods.get_SHA256(HelperMethods.start_process(["dmidecode", "-s", "system-uuid"]).decode('utf-8'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/licensing/internal.py", line 57, in start_process
    process = Popen(command, stdout=PIPE)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dmidecode': 'dmidecode'

**Comment by artemlos** [comment]
@cypri99 on what OS does this occur?

**Comment by kobkrit** [comment]
MacOS

**Comment by Eloque** [comment]
Found it and why.

In the method.py bit, it checks this code to determine platform:

```
        if "Windows" in platform.platform():
            return HelperMethods.get_SHA256(HelperMethods.start_process(["cmd.exe", "/C", "wmic","csproduct", "get", "uuid"]))
        elif "Mac" in platform.platform():               
            res = HelperMethods.start_process(["system_profiler","SPHardwareDataType"]).decode('utf-8')
            HelperMethods.get_SHA256(res[res.index("UUID"):].strip())
        elif "Linux" in platform.platform():
            return HelperMethods.get_SHA256(HelperMethods.start_process(["dmidecode", "-s", "system-uuid"]))
        else:
            return HelperMethods.get_SHA256(HelperMethods.start_process(["dmidecode", "-s", "system-uuid"]).decode('utf-8'))
```

It want's to check if "Mac" is in platform.platform(), that won't work because for instance on my machine, it platform.platform() gives "'Darwin-18.6.0-x86_64-i386-64bit".

A solution would be to better check for Mac Os, at see if "Darwin" is in there.

**Comment by artemlos** [comment]
@Eloque thanks for the fix 👍 It's now available in v.10 of the python client (https://github.com/Cryptolens/cryptolens-python/releases/tag/v_10)
