### ISSUE TITLE
Can I somehow add this to my program?

### ISSUE THREAD

**Issue by malakhov-beep** [Cryptolens/cryptolens-python#30]
Sorry for the stupid question, but how can you add it to your program?
I started programming recently, and I need to check the license key, but I'm not good at it. Can I somehow add this to my program?

**Comment by artemlos** [comment]
@malakhov-beep Hi! It depends on the Python version. If you are using Python 3, you can install the package through PyPI, e.g. running "pip install licensing" (more [docs](https://docs.python.org/3/installing/index.html)). Once this is done, you can use the following code snippet (https://github.com/cryptolens/cryptolens-python#key-verification) to verify a license.

Please let me know if you have any questions 👍

**Comment by malakhov-beep** [comment]
Okay, how  change this code to validate the key entered by the user?
could you give an example?

(I roughly understand how to do this, but I can't)

**Comment by vvalkonen** [comment]
@malakhov-beep it is described in the the above-mentioned documentation(s)
