### ISSUE TITLE
MachineCode changing after reboot

### ISSUE THREAD

**Issue by lucabianchi91** [Cryptolens/cryptolens-python#36]
Hi,
I have a RasperryPi wiith OpenWRT OS, and I notice that at each reboot `Helpers.GetMachineCode()` changes, 
making it impossible to limit licenses to a certain numbers of machines.

**Comment by artemlos** [comment]
Hi! Thanks for reporting this issue. Sorry for a late reply.

I think this might be resolved if the serial number is used for identification instead. We released support for it in our .NET SDK but it's not yet part the Python SDK. We can release this fix in the Python SDK too.

To make sure the serial number solution will work, could you please check if the value of "Serial" is the same after reboot when you run the following command:

```
cat /proc/cpuinfo
```

The "serial" should be located in the end of the output from the command above. For example, when I run it on my own RPI, I get the following output:

![image](https://user-images.githubusercontent.com/6392760/99371815-b118f700-28bf-11eb-9727-cb4f0f96fbc1.png)


@lucabianchi91

**Comment by lucabianchi91** [comment]
Hi, thanks for the reply.
I verified as requested `/proc/cpuinfo`and on RaspberryPi the Serial remains the same after reboot.
BUT
I tried also on a NanoPi NEO Core (OpenWrt OS) and sadly there is no Serial in `/proc/cpuinfo` and `Helpers.GetMachineCode()` changes at reboot. On Nanopi:
```
root@OpenWrt:~# cat /proc/cpuinfo
processor	: 0
BogoMIPS	: 48.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 1
BogoMIPS	: 48.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 2
BogoMIPS	: 48.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 3
BogoMIPS	: 48.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4
```

**Comment by artemlos** [comment]
@lucabianchi91, thanks for the feedback!

How does the output look like when you run the following command on NanoPi NEO Core?

```
findmnt --output=UUID --noheadings --target=/boot
```

I think this solution can be used on non-RPI devices.

**Comment by lucabianchi91** [comment]
With target, no output.
Without target, there is something but with a lot of empty lines, which I post below in case you need to parse.
This string is the same after reboot, BUT it is the same on all the NanoPi I have, so I don't think it can be used as identifier.
It's becoming an hard task ...
```
root@OpenWrt:~# findmnt --output=UUID --noheadings --target=/boot
root@OpenWrt:~# findmnt --output=UUID --noheadings
ff313567-e9f1-5a5d-9895-3ba130b4a864


















ff313567-e9f1-5a5d-9895-3ba130b4a864



root@OpenWrt:~# 
```

**Comment by artemlos** [comment]
@lucabianchi91 thanks again for the feedback!

I think we can solve the identification of NanoPi in two ways, either by relying on the MAC address or by computing a random UUID which is stored somewhere on the device. I haven't been able to find a way to retrieve a UUID the same way it can be done on a Raspberry PI.

If you run `/sbin/ifconfig`, could you please check if the MAC address stays the same after boot for the ethernet adapter? Theoretically, it should, but I just want to make it's the case on NanoPi.

![image](https://user-images.githubusercontent.com/6392760/99982554-03b84e80-2dab-11eb-9362-2eb4ce9d484b.png)

**Comment by lucabianchi91** [comment]
Hi, thanks for the reply. Yes, all mac addresses are unique and fixed. `eth0` is not always up, so it's better to use `ifconfig -a`.
Or better, `ip a` since it's installed by default on many systems, contrarily to `ifconfig`.

Since mac addresses can be easily changed with `ifconfig`, would it be possible to let the developer specify which network interface to be used for `MachineId` computation?

For example, let's say we have devices communicating over a WiFi mesh network (all using interface `wlan1`).
A cheater could clone the SD Card where the OS resides, modify eth0's mac address and be able to work around the protection (since `eth0` is not used for communications). However, he couldn't set the same `wlan1` mac address and have the two devices communicate with each other. So in this case the developer would choose `wlan1` as seed for `MachineId` computation to protect his code.

**Comment by artemlos** [comment]
@lucabianchi91, thanks for the feedback.

That would be possible. From the perspective of the Web API, the end user identifier can be set to an arbitrary string value. It's up to the client application to specify it.

I'm thinking that we might be able to use `uuid` in Python to get the MAC address of the network interface that is actively used.

If you run the following code, do you get the MAC address of the actively used interface (in your case, I think it would be `wlan1`)?

```python
import uuid

print (':'.join(['{:02x}'.format((uuid.getnode() >> ele) & 0xff) for ele in range(0,8*6,8)][::-1]))
```

**Comment by lucabianchi91** [comment]
```
root@OpenWrt:~# python3 test_uuid.py 
70:f1:1c:44:af:4a
root@OpenWrt:~# ifconfig 
br-72c019320e42 Link encap:Ethernet  HWaddr 02:42:E8:EC:BA:1B  
          inet addr:172.172.0.1  Bcast:172.172.255.255  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

docker0   Link encap:Ethernet  HWaddr 02:42:C6:72:DB:2C  
          inet addr:172.17.0.1  Bcast:172.17.255.255  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

dummy0    Link encap:Ethernet  HWaddr 26:BF:60:28:BB:E4  
          inet6 addr: fe80::c2a9:2625:b9c:3fac/64 Scope:Link
          UP BROADCAST RUNNING NOARP  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:922 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:313148 (305.8 KiB)

eth0      Link encap:Ethernet  HWaddr 02:01:E8:F2:5C:EE  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:25 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:788 errors:0 dropped:0 overruns:0 frame:0
          TX packets:788 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:69968 (68.3 KiB)  TX bytes:69968 (68.3 KiB)

wlan0     Link encap:Ethernet  HWaddr 70:F1:1C:44:AF:4A  
          inet addr:192.168.10.49  Bcast:192.168.10.255  Mask:255.255.255.0
          inet6 addr: fe80::72f1:1cff:fe44:af4a/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:506831 errors:0 dropped:0 overruns:0 frame:0
          TX packets:93892 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:110659813 (105.5 MiB)  TX bytes:17911718 (17.0 MiB)

wlan0:0   Link encap:Ethernet  HWaddr 70:F1:1C:44:AF:4A  
          inet addr:192.168.11.49  Bcast:192.168.11.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

wlan1     Link encap:Ethernet  HWaddr AC:64:CF:00:00:49  
          inet addr:192.168.3.1  Bcast:192.168.3.255  Mask:255.255.255.0
          inet6 addr: fe80::ae64:cfff:fe00:49/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:4 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```
Apparently `uuid.getnode()` has chosen `wlan0` (which is fine for my case). 
I'd say that this is a good solution in general, and if the developer is not happy he could always redefine the method :-)

**Comment by artemlos** [comment]
Thanks @lucabianchi91 :)

I added a new parameter `custom_machine_code` to `IsOnRightMachine` so that it supports other machine code definitions (https://github.com/Cryptolens/cryptolens-python/commit/85456a7587dae6b9e678e008732ad58d52bf866a).

There is also a method to retrieve the MAC address (using `uuid.getnode()`), i.e. `Helpers.GetMACAddress()` (https://github.com/Cryptolens/cryptolens-python/commit/78508cfd51789ee496ffe1ee9048af005ab757b9).

**Comment by lucabianchi91** [comment]
Thank you!
