### ISSUE TITLE
Implement CreateSessionPM

### ISSUE THREAD

**Issue by artemlos** [Cryptolens/cryptolens-python#38]
https://app.cryptolens.io/api/paymentform/CreateSession

**Comment by Tomas1337** [comment]
High artem. Thanks for this. 
Right now i'm just trying to get this working using the link directly. 

Is this right? 
> https://app.cryptolens.io/api/paymentform/CreateSession?PaymentFormId=750&Price=150.0&Currency=USD&Expires=50
This returns:
{"result":1,"message":"Unable to authenticate."}

Are access tokens required for this?

Maybe if I could get that working I can help with the creating the method.

**Comment by Tomas1337** [comment]
Okay got this to work by inputting the first parameter to be an access_token with paymentform permission.

**Comment by artemlos** [comment]
@Tomas1337 Nice to hear that it was resolved :)

**Comment by artemlos** [comment]
@Tomas1337 The create_session is now part of the Python SDK: https://github.com/Cryptolens/cryptolens-python/commit/7ae22ba13b0a391bc572b01d90ee6c7a292ff437

**Comment by artemlos** [comment]
Closing the issue since the error appears to be resolved.
