### ISSUE TITLE
Payment Form not completing?

### ISSUE THREAD

**Issue by Tomas1337** [Cryptolens/cryptolens-python#39]
After entering a payment form on the webpage and going through paypal, the backend doesnt seem to send out the requests nor a confirmation email nor call the AddCustomer method

I've doubled checked the request URL under the payment forms and it seems correct when I input it directly to the browser. 

Not sure what the disconnect is. Btw, this is on a sandboy Paypal scenrio.

**Comment by artemlos** [comment]
Thank you for the question and I'm sorry for a late reply from our side. I think we might have already answered this on Intercom. In case the issue persists, please send us an email at support@cryptolens.io. This will make it possible to troubleshoot it further and allow us to look into the specific form where this issue occured.
