### ISSUE TITLE
keys don’t become invalid when they have “expired”?

### ISSUE THREAD

**Issue by mhmehdi** [Cryptolens/cryptolens-python#44]

**Comment by artemlos** [comment]
Hi, thanks for the question.

By default, licenses will keep working after the expiration, unless
a) the expiration date is checked in the code
b) the license is marked as time-limited and "block expired licenses" is set to true.

I will include a wiki article that I think might helpful: https://help.cryptolens.io/web-interface/feature-definitions

Please let us now should you have any other questions, either by writing to us here on GitHub or contacting us at support@cryptolens.io.
