### ISSUE TITLE
WMIC used to generate machine code is deprecated

### ISSUE THREAD

**Issue by pmnforce** [Cryptolens/cryptolens-python#50]
Hi

I'd just like to make you aware of the fact that WMIC (used for generating machine code on Windows) is being deprecated (https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-deprecated-features). Would be nice to adapt to another approach before the tool is completely removed from Windows :).

Best regards
Peter

**Comment by artemlos** [comment]
Hi Peter,

Thanks for letting us know :)

I think we might be able to retrieve the UUID using PS instead, which was tested in the NodeJs client, i.e., as follows:

```ps
cmd /c powershell.exe -Command "(Get-CimInstance -Class Win32_ComputerSystemProduct).UUID"
```

We will review the link more thoroughly and release an update soon.

Thanks again!

@pmnforce

**Comment by pmnforce** [comment]
Sounds good :). And thanks for the quick reply!

**Comment by artemlos** [comment]
@pmnforce We have now updated the UUID source so that it does not rely on WMIC, available in the latest release (https://github.com/Cryptolens/cryptolens-python/releases/tag/v_34)
