### ISSUE TITLE
How to save licenses?

### ISSUE THREAD

**Issue by zhang-qiang-github** [Cryptolens/cryptolens-python#53]
`cryptolens-python` is a very wonderful project, and I have a question about how to save licenses.

In the introduction, the license is recommanded to saved as:

```
# res is obtained from the code above
if result[0] != None:
    # saving license file to disk
    with open('licensefile.skm', 'w') as f:
        f.write(result[0].save_as_string())
```

However, the saved `licensefile.skm` may be deleted by user. If the `licensefile.skm` is deleted, the computer would be treated as a new one.

How can I save `result[0]` that can not be changed by user?

Thank you very much in advance.

**Comment by artemlos** [comment]
@zhang-qiang-github thanks for the question. I'm really happy that you like it :)

To prevent this, it's important to ensure that the license file is activated on that machine, for example, using node-locking: https://help.cryptolens.io/licensing-models/node-locked

When the license is activated on that machine, you can check that using Helpers.[IsOnRightMachine](https://github.com/Cryptolens/cryptolens-python/blob/master/licensing/methods.py#L1013) after that a license file is loaded.

**Comment by artemlos** [comment]
I checked the code on the main page, and in the code that follows after saving the license file to file already includes this check:

```python
# read license file from file
with open('licensefile.skm', 'r') as f:
    license_key = LicenseKey.load_from_string(pubKey, f.read())
    
    if license_key == None or not Helpers.IsOnRightMachine(license_key, v=2):
        print("NOTE: This license file does not belong to this machine.")
    else:
        print("Feature 1: " + str(license_key.f1))
        print("License expires: " + str(license_key.expires))
```
