### ISSUE TITLE
update the token values

### ISSUE THREAD

**Issue by IAGirl-dev** [Cryptolens/cryptolens-python#54]
hello, i'd like to know if it is possible to change the tokes value, after the user utilization ( in python) , am trying to develop a softwere where the price of the subcription is based on the number of images that i modify for the user, after identification and extracting the value of the token that the user get from it subsription how could I update it please?

**Comment by artemlos** [comment]
@IAGirl-dev Thanks for the question! I think that this can be accomplished using data objects. I will include a guide with more information: https://help.cryptolens.io/licensing-models/usage-based

Please let us know should you have any questions, either here on GitHub or by emailing us at support@cryptolens.io.
