### ISSUE TITLE
decrement_int_value_to_key function doesn't exists

### ISSUE THREAD

**Issue by IAGirl-dev** [Cryptolens/cryptolens-python#55]
hello, as I am trying to use cryptolens to decriment a data object int value however in the code you displayed on github i can't seem to fine the function decrement int value to key in the DATA Class, i can oly find the the increment_int_value_to_key

**Comment by artemlos** [comment]
@IAGirl-dev thanks for the feedback!

I added a PR with the method. It will be reviewed one more time and then pushed to the master branch.

**Comment by artemlos** [comment]
@IAGirl-dev The changes are now live. Thanks again for the feedback!
