### ISSUE TITLE
add parameters when calling the payement form in the request URL

### ISSUE THREAD

**Issue by IAGirl-dev** [Cryptolens/cryptolens-python#58]
Hello I have a question,
Is it possible to add parameters when calling the payement form, I'm trying to use the payement per use , where I create a data object when creating a key, then this key helps to authentify the person on my software . When reashing the value 0 the user could recharge the old key without creating a new key, I create a payement form for  the first payement : the key is being created and another one for recharging the this key.
however I can't figure out  how to add the key and the Id of the data object in the URL form in URL that should be called after succeding the payement .
Is there a way to do this please ?

**Comment by artemlos** [comment]
Hi, thanks for the question! I think that you could use the [custom field](https://help.cryptolens.io/payment-form/custom-field) in a payment form to pass on a license key when they are about to upgrade. The payment form that is responsible for upgrading their licenses (in your case, adding credits), would only need to call [SetIntValue](https://app.cryptolens.io/docs/api/v3/SetIntValue) method, with method parameters in _Method 2 (key specific)_. The custom field of the payment form can be used to store the license key string, which can later be passed to SetIntValue method. There is no need to pass on the ID of a license in this case, key string will suffice. I would also recommend to make sure that Key Lock = -1 for the access token that is being used.
