### ISSUE TITLE
The license does not work: Unable to authenticate

### ISSUE THREAD

**Issue by sabhashanki** [Cryptolens/cryptolens-python#60]
Hi Team,
I face difficulty in authenticating the key and adding the machine for licensing. Below is the code referenced from your github documentation. I have already generated RSA public key, auth key, product code and key, when used im getting "The license does not work: Unable to authenticate." error. I have also tried manually adding the machine code in the licensing page and tried verifying using another code block mentioned in github documentation, still i get the same error

`

RSAPubKey = rsakey
auth = authkey

result = Key.activate(token=auth,
                   rsa_pub_key=RSAPubKey,
                   product_id=idcode, 
                   key=keygen,
                   machine_code=Helpers.GetMachineCode(v=2))
print(Helpers.GetMachineCode(v=2))

if result[0] == None or not Helpers.IsOnRightMachine(result[0], v=2):
    # an error occurred or the key is invalid or it cannot be activated
    # (eg. the limit of activated devices was achieved)
    print("The license does not work: {0}".format(result[1]))
else:
    # everything went fine if we are here!
    print("The license is valid!")
    license_key = result[0]
    print("Feature 1: " + str(license_key.f1))
    print("License expires: " + str(license_key.expires))

`

to verify after manually adding the machine code in licensing

`
RSAPubKey = rsatoken

with open('/home/ms/Downloads/ActivationFile20230301.skm', 'r') as f:
    license_key = LicenseKey.load_from_string(RSAPubKey, f.read())
    
    if license_key == None or not Helpers.IsOnRightMachine(license_key, v=2):
        print("NOTE: This license file does not belong to this machine.")
    else:
        print("Feature 1: " + str(license_key.f1))
        print("License expires: " + str(license_key.expires))

`

**Comment by artemlos** [comment]
Hi, thanks for writing to us. It sounds like the problem you are experiencing is related to API access. Unable to authenticate means that the access token contains a typo or does not exist. I would suggest to review the following section in the FAQ on how to troubleshoot them: https://help.cryptolens.io/faq/index#troubleshooting-api-errors

Please let us know should you have any other questions!
