### ISSUE TITLE
Hello, I wonder why the expiration date has come but the key is still valid .How to automatically block it when it expires

### ISSUE THREAD

**Issue by TanMink** [Cryptolens/cryptolens-python#62]
![image](https://github.com/Cryptolens/cryptolens-python/assets/95482331/e32e5faf-139f-414e-ba0c-65d8b2550716)
![image](https://github.com/Cryptolens/cryptolens-python/assets/95482331/c4b5c46a-e4de-429b-b708-60f8ef6225f7)

**Comment by artemlos** [comment]
Hi @TanMink, thanks for the question!

Licenses can automatically be blocked using the following feature: https://help.cryptolens.io/faq/index#blocking-expired-licenses. I would also suggest the following article: https://help.cryptolens.io/web-interface/keys-that-dont-expire

Please let us know should you have any other questions, either here in GitHub or by reaching out to us at support@crytolens.io.

Best,
Artem
