### ISSUE TITLE
Machine Code None

### ISSUE THREAD

**Issue by Rirynn** [Cryptolens/cryptolens-python#64]
Hi! I created a test license for 5 PCs and it seems that on one of them when I try to activate the license it appears that the license is invalid and on the website in the Machine Code section it appears as None but on the other two PCs it works.

here is the script in python

RSAPubKey = "<RSAKeyValue><Modulus>ydXaE5whpDDNLPX+wy1ikMHWx4zxGOBECFJCD9x2ye1iQDjcGf+y1ZRaw+5XLUVOkmk0RB04E3Wt1tRpDbTrbxpQx7MwNorjE/0f9rzOmbSElrTt7Nqk1LR+ywa9/SSEDaJAHGxmHw2VSDKdolfr8uzYmsUBEOlt+NUKCmE/lfArtkLORBHsoP+mC8a7RbH3g9CfA8RUQ/hiQbMDpDiJF+rRUfxWJRUhWFLiDCMNc+opbAu56JOMPS/0nI+44vag08IIuYqNX3wYp7QEurJNGCNFl/X4Aqcy/mbVbcCFoO0TzKo7l45EM+KeK5WGF7PLZQpr98SPRFtRvgaeXl5Vlw==</Modulus><Exponent>AQAB</Exponent></RSAKeyValue>"
auth = "WyI1NjQ2ODU4NyIsIkJJUTFvRDdLKzV5dThJb3RtVVBMS0NEU0NKd0FOakdaVVFURlJNWGwiXQ=="

result = Key.activate(token=auth,\
                   rsa_pub_key=RSAPubKey,\
                   product_id=21267, \
                   key="FRGLJ-ZUKAZ-JNJYT-RNDUW",
                   machine_code=Helpers.GetMachineCode(v=2))

if result[0] == None or not Helpers.IsOnRightMachine(result[0], v=2):
    # an error occurred or the key is invalid or it cannot be activated
    # (eg. the limit of activated devices was achieved)
    print("The license does not work: {0}".format(result[1]))
    msg = CTkMessagebox(title="Error", message="Licență invalidă!", icon="cancel")
    msg.wait_window()
else:
    # everything went fine if we are here!
    print("The license is valid!")

**Comment by artemlos** [comment]
Hi @Rirynn!

What is the value of Helpers.GetMachineCode(v=2) on the machines where it's not possible to activate? Thanks!

**Comment by Rirynn** [comment]
Value is None.

**Comment by artemlos** [comment]
It sounds like there is an issue with that method on those machines, for example, due to lack of permissions. Could you please try the following method  instead? https://github.com/Cryptolens/cryptolens-python/blob/master/licensing/methods.py#L1158C20-L1158C20

I.e. Helpers.GetMacAddress.

Thanks!

**Comment by Rirynn** [comment]
Yes, the problem was lack of permissions. Thanks
