### ISSUE TITLE
Problem with Helpers.GetMachineCode(v=2) on Windows

### ISSUE THREAD

**Issue by asceenl** [Cryptolens/cryptolens-python#69]
When we run. We get a machine code of None on Windows.

If we run the associated command that is executed in Powershell:

Powershell > Get-CimInstance -Class Win32_ComputerSystemProduct

Get-CimInstance : Invalid Class

So no output is sent to stdout, and "" goes to None in the callers. Do you know the reason for this and a way to solve? This is rather urgent. It is our first client we would like to get running with our software.

Thanks in advance for your answer.

**Comment by artemlos** [comment]
@asceenl 

It sounds like a likely issue to this could be due to WMI repository being corrupt. 

Would it be possible to execute the following command on their site:

`winmgmt /verifyrepository`

What does that command return?

Thanks!

**Comment by asceenl** [comment]
Dear Artemlos,

This is the output:

![image](https://github.com/Cryptolens/cryptolens-python/assets/32465327/438cd5c8-ab76-4f49-a637-d2c4b0d7c23f)

**Comment by asceenl** [comment]
Should I run it in Administrator mode?

**Comment by hugocarnide** [comment]
I have the similar issue with a customer. 
I will request to run the verify command to help that investigation

As per reading the library, I figure out a case not available to be used.
The comparison made here https://github.com/Cryptolens/cryptolens-python/blob/master/licensing/methods.py#L1438
It do not permit to compare a None value to a string 'None' if we want to setup that value in the licence.

**Comment by artemlos** [comment]
@hugocarnide Thank you! Please let me know how it goes.

I would like to ask, with regards to https://github.com/Cryptolens/cryptolens-python/blob/master/licensing/methods.py#L1438, is the issue that if current_mid===None (presumably because the machine code was not computed correctly), you would like that to return false if the one of the machines has ( act_machine.Mid) has the value None or empty string?

**Comment by hugocarnide** [comment]
Thanks @artemlos for reading my question. 

The feature could be a failover to have another way to compute the machine code.
https://github.com/keygen-sh/py-machineid/blob/master/machineid/__init__.py#L86

For this case, I would like to be able to register None as deviceId and having the method comparing that and letting continue. It is an exceptional case until we figure out what is happening.

**Comment by artemlos** [comment]
A new release is now available which fallbacks on the machineGUID obtained from the registry on Windows. Please note that a user may be able to change this if they have sufficient permissions.

@hugocarnide if possible, could you please let me know if it works now for your client?
@asceenl I would suggest to test the updated version of GetMachineCode method which will fallback on MachineGUID in case the WMI is broken for some reason on the client's machine. Please keep in mind that a user may be able to change machineGUID and that it can reset if they reinstall the operating system.

**Comment by artemlos** [comment]
@hugocarnide Thank you for the link in your previous message by the way. It was very helpful.
