### ISSUE TITLE
Python/OS compatibility

### ISSUE THREAD

**Issue by ubmarco** [Cryptolens/cryptolens-python#71]
Thanks for this library. I'm using it in a [pants](https://www.pantsbuild.org) project, but when building a pex I get

```
No pre-built wheel was available for licensing 0.45.
Successfully built the wheel licensing-0.45-py3-none-any.whl from the sdist licensing-0.45.tar.gz but it is not compatible with the requested foreign target complete platform cp311-cp311-manylinux_2_35_x86_64.
You'll need to build a wheel from licensing-0.45.tar.gz on the foreign target platform and make it available to Pex via a `--find-links` repo or a custom `--index`.
```
I think this due to the classifiers in [setup.py](https://github.com/Cryptolens/cryptolens-python/blob/master/setup.py#L18):
```
    'Programming Language :: Python :: 3',      #Specify which pyhton versions that you want to support
    'Programming Language :: Python :: 3.4',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
```

What about 3.7 to 3.12, are they also supported? What about the OS specifiers, does it support all OS's?

**Comment by ubmarco** [comment]
This is the `PKG-INFO` of the 0.45 sdist:
```
Metadata-Version: 1.1
Name: licensing
Version: 0.45
Summary: Client library for Cryptolens licensing Web API.
Home-page: https://cryptolens.io
Author: Cryptolens AB
Author-email: support@cryptolens.io
License: MIT
Download-URL: https://github.com/Cryptolens/cryptolens-python/archive/v_45.tar.gz
Description: UNKNOWN
Keywords: software licensing,licensing library,cryptolens
Platform: UNKNOWN
Classifier: Intended Audience :: Developers
Classifier: Topic :: Software Development :: Build Tools
Classifier: License :: OSI Approved :: MIT License
Classifier: Programming Language :: Python :: 3
Classifier: Programming Language :: Python :: 3.4
Classifier: Programming Language :: Python :: 3.5
Classifier: Programming Language :: Python :: 3.6
```

**Comment by artemlos** [comment]
@ubmarco  Thank you for pointing this out. I'm sorry for not have replied earlier. A few changes were made to the setup.py in https://github.com/Cryptolens/cryptolens-python/commit/a481e3d1ca54845c226ef306e0ee4f7978632975 that should hopefully resolve this. Firstly, the list of Python versions was extended. Secondly, a list of supported platforms was added. I think the issue could have been caused by the latter, since we already specify that the package works with Python 3, however, all the versions are now explicitly specified.

**Comment by artemlos** [comment]
A new release is now available which should address the issue caused by missing Python versions.

@ubmarco
